# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' read the signals from a MIT database file
#' @param  filename The path to the signal file, without extension
#' @return a Matrix object with one signal per row
#' @note This function needs to be called from the directory where the file resides. Use getvec to go over this restriction
getvec_ <- function(filename) {
    .Call('wfdb4R_getvec_', PACKAGE = 'wfdb4R', filename)
}

